
project_id = "zxstilrzamzlgswgwlpp"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = [
    "https://localhost:3000",
    "https://localhost:3000/auth/callback",
    "https://localhost:3000/auth/reset-password",
    "https://localhost:3000/confirmation",
    "https://localhost:3000/payment/success",
    "https://localhost:3000/payment/redirect",
    "https://settlementwins.com",
    "https://settlementwins.com/auth/callback",
    "https://settlementwins.com/auth/reset-password",
    "https://settlementwins.com/confirmation",
    "https://settlementwins.com/payment/success",
    "https://settlementwins.com/payment/redirect",
    "https://www.settlementwins.com",
    "https://www.settlementwins.com/auth/callback",
    "https://www.settlementwins.com/auth/reset-password",
    "https://www.settlementwins.com/confirmation",
    "https://www.settlementwins.com/payment/success",
    "https://www.settlementwins.com/payment/redirect",
    "https://settlement-wins-web.vercel.app",
    "https://settlement-wins-web.vercel.app/auth/callback",
    "https://settlement-wins-web.vercel.app/auth/reset-password",
    "https://settlement-wins-web.vercel.app/confirmation",
    "https://settlement-wins-web.vercel.app/payment/success",
    "https://settlement-wins-web.vercel.app/payment/redirect",
    "https://payment-redirect-preview.vercel.app",
    "https://payment-redirect-preview.vercel.app/auth/callback",
    "https://payment-redirect-preview.vercel.app/auth/reset-password",
    "https://payment-redirect-preview.vercel.app/confirmation",
    "https://payment-redirect-preview.vercel.app/payment/success",
    "https://payment-redirect-preview.vercel.app/payment/redirect"
]
jwt_expiry = 3600
enable_signup = true

[analytics]
enabled = false
port = 54327
vector_port = 54328

[functions]
[functions.check-payment-status]
verify_jwt = false
[functions.create-checkout-session]
verify_jwt = false
[functions.webhook-handler]
verify_jwt = false
[functions.fix-settlement]
verify_jwt = false
