
project_id = "zxstilrzamzlgswgwlpp"

[functions]
[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = false

[functions.verify-subscription]
verify_jwt = false
