
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Environment-specific configuration
const getSupabaseConfig = () => {
  const environment = import.meta.env.VITE_APP_ENV || 'development';
  
  // Default to development values
  let supabaseUrl = "https://zxstilrzamzlgswgwlpp.supabase.co";
  let supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4c3RpbHJ6YW16bGdzd2d3bHBwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1MDAzOTYsImV4cCI6MjA1NjA3NjM5Nn0.WiqcQcQnxfGhE9BwCorEYdZbV3ece7ITv2OwCUufpwI";

  if (environment === 'staging') {
    // Staging environment values (you'll need to set these up)
    supabaseUrl = import.meta.env.VITE_SUPABASE_URL_STAGING || supabaseUrl;
    supabaseKey = import.meta.env.VITE_SUPABASE_KEY_STAGING || supabaseKey;
    console.log('Using staging Supabase environment');
  } else if (environment === 'production') {
    // Production environment values
    supabaseUrl = import.meta.env.VITE_SUPABASE_URL_PRODUCTION || supabaseUrl;
    supabaseKey = import.meta.env.VITE_SUPABASE_KEY_PRODUCTION || supabaseKey;
    console.log('Using production Supabase environment');
  } else {
    console.log('Using development Supabase environment');
  }

  return { supabaseUrl, supabaseKey };
};

const { supabaseUrl, supabaseKey } = getSupabaseConfig();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);
